"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.localServerURL = exports.localClientURL = exports.GENERIC_ALPHANUMERIC_REGEX = exports.PASSSWORD_REGEX = exports.USER_ID_REGEX = exports.NAME_REGEX = exports.MAX_ID_LENGTH = exports.MIN_ID_LENGTH = exports.MIN_NAME_LENGTH = exports.MAX_NAME_LENGTH = exports.MAX_PROJECT_NAME_CHARS = exports.MAX_PROJECT_DESCRIPTION_CHARS = exports.MIN_PASSWORD_LENGTH = exports.MAX_PASSWORD_LENGTH = void 0;
exports.MAX_PASSWORD_LENGTH = 16;
exports.MIN_PASSWORD_LENGTH = 8;
exports.MAX_PROJECT_DESCRIPTION_CHARS = 75;
exports.MAX_PROJECT_NAME_CHARS = 50;
exports.MAX_NAME_LENGTH = 16;
exports.MIN_NAME_LENGTH = 1;
exports.MIN_ID_LENGTH = 1;
exports.MAX_ID_LENGTH = 16;
exports.NAME_REGEX = '^[A-Za-z\\s\-]+$';
exports.USER_ID_REGEX = '^[A-Za-z0-9]+$';
exports.PASSSWORD_REGEX = '^[A-Za-z0-9_!@#$%*]+$';
exports.GENERIC_ALPHANUMERIC_REGEX = '^[A-Za-z\\s0-9]+$';
exports.localClientURL = 'http://localhost:5173';
exports.localServerURL = 'http://localhost:8080';
